// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9nk-KSip861roN3rr311uUt87n3vNV_U',
    appId: '1:270462597470:web:b7e9abf7335de9962c37cf',
    messagingSenderId: '270462597470',
    projectId: 'sascma-88f4d',
    authDomain: 'sascma-88f4d.firebaseapp.com',
    storageBucket: 'sascma-88f4d.firebasestorage.app',
    measurementId: 'G-ZZPDBVKQZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOaxTIhgn1cJBKkbuU10APA1X1U5IW1qg',
    appId: '1:270462597470:android:e309c4c8586895d02c37cf',
    messagingSenderId: '270462597470',
    projectId: 'sascma-88f4d',
    storageBucket: 'sascma-88f4d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfqxWVYyb1JL2GSiEOyudPS4ioGpjWAOo',
    appId: '1:270462597470:ios:23f06fe32f1e2b792c37cf',
    messagingSenderId: '270462597470',
    projectId: 'sascma-88f4d',
    storageBucket: 'sascma-88f4d.firebasestorage.app',
    iosBundleId: 'com.example.sascma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfqxWVYyb1JL2GSiEOyudPS4ioGpjWAOo',
    appId: '1:270462597470:ios:23f06fe32f1e2b792c37cf',
    messagingSenderId: '270462597470',
    projectId: 'sascma-88f4d',
    storageBucket: 'sascma-88f4d.firebasestorage.app',
    iosBundleId: 'com.example.sascma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9nk-KSip861roN3rr311uUt87n3vNV_U',
    appId: '1:270462597470:web:396c7d238b0c40672c37cf',
    messagingSenderId: '270462597470',
    projectId: 'sascma-88f4d',
    authDomain: 'sascma-88f4d.firebaseapp.com',
    storageBucket: 'sascma-88f4d.firebasestorage.app',
    measurementId: 'G-B58F1WTV4K',
  );

}